# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, default=b'', null=True)),
                ('camera', models.TextField(blank=True, default=b'', max_length=255, null=True)),
                ('photography_type', models.CharField(choices=[(b'portrait', b'Portrait'), (b'landscape', b'Landscape'), (b'nature', b'Nature'), (b'family', b'Family'), (b'travel', b'Travel'), (b'art', b'Art'), (b'food', b'Food')], default=b'art', max_length=255)),
                ('friends', models.ManyToManyField(related_name='friend_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
