# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='fav_photo',
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[(b'portrait', b'Portrait'), (b'landscape', b'Landscape'), (b'nature', b'Nature'), (b'family', b'Family'), (b'travel', b'Travel'), (b'art', b'Art'), (b'food', b'Food')], default=b'art', max_length=30),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.TextField(default=b'', max_length=100),
        ),
    ]
