# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20160412_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.TextField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[(b'portrait', b'Portrait'), (b'landscape', b'Landscape'), (b'nature', b'Nature'), (b'family', b'Family'), (b'travel', b'Travel'), (b'art', b'Art'), (b'food', b'Food')], default=b'art', max_length=255),
        ),
    ]
