# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='media/img_files/puppy1.jpg', upload_to=b''),
        ),
    ]
