# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_file',
            field=models.ImageField(default=datetime.datetime(2016, 4, 12, 23, 55, 25, 672049, tzinfo=utc), upload_to=b'img_files'),
            preserve_default=False,
        ),
    ]
