# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_photo_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
