# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20160423_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default=b'/Users/admin-1/imager/django-imager/imagersite/media/img_files/puppy1.jpg', upload_to=b''),
        ),
    ]
