# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20160413_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[(b'Private', b'Private'), (b'Shared', b'Shared'), (b'Public', b'Public')], default=b'Private', max_length=255),
        ),
    ]
