# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20160423_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default=b'img_files/upload.png', upload_to=b''),
        ),
    ]
