# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_auto_20160423_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='img_files/upload.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('Private', 'Private'), ('Shared', 'Shared'), ('Public', 'Public')], default='Private', max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img_file',
            field=models.ImageField(upload_to='img_files'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(choices=[('Private', 'Private'), ('Shared', 'Shared'), ('Public', 'Public')], default='Private', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
