# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20160511_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='img_files/upload.png', upload_to='img_files'),
        ),
    ]
