# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0008_auto_20160418_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albumd_covered', to='imager_images.Photo'),
        ),
    ]
