# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0014_remove_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covered_albums', to='imager_images.Photo'),
        ),
    ]
