# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0016_auto_20160419_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img_file',
            field=models.ImageField(upload_to=b'../img_files'),
        ),
    ]
