# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0017_auto_20160420_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img_file',
            field=models.ImageField(upload_to=b'/media/img_files'),
        ),
    ]
