# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0019_auto_20160420_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('Private', 'Private'), ('Shared', 'Shared'), ('Public', 'Public')], default='Private', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img_file',
            field=models.ImageField(upload_to='img_files'),
        ),
    ]
