# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0020_auto_20160421_2358'),
        ('imager_images', '0020_auto_20160421_2336'),
    ]

    operations = [
    ]
