# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0022_auto_20160422_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(default=b'upload.png', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covered_albums', to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
