# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0025_auto_20160422_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default=b'media/upload.png', upload_to=b''),
        ),
    ]
