# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0026_auto_20160422_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default=b'media/img_files/flower.jpg', upload_to=b''),
        ),
    ]
