# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0027_auto_20160423_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
    ]
